services:
  db:
    image: postgres:16
    container_name: fatmug_demo_local_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env/.env.local.db
    networks:
      - backend_network
  
  redis:
    image: redis:latest
    container_name: fatmug_demo_local_redis
    ports:
      - "6379:6379"
    networks:
      - backend_network
  
  backend:
    container_name: fatmug_demo_local_backend
    build:
      context: ./backend
      dockerfile: ../compose/local/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
      - ./logs/backend:/var/log/app
    env_file:
      - ./.env/.env.local.django
      - ./.env/.env.local.db
    depends_on:
      - db
      - redis
    networks:
      - backend_network
  
  frontend:
    container_name: fatmug_demo_local_frontend
    build:
      context: ./frontend
      dockerfile: ../compose/local/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env/.env.local.frontend
    depends_on:
      - backend
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
