# Generated by Django 5.1.1 on 2024-09-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidapp', '0002_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
