# Generated by Django 5.1.1 on 2024-09-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidapp', '0003_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='vidapp.video'),
        ),
    ]
