# Generated by Django 5.1.1 on 2024-09-14 07:42

import core.vidapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidapp', '0004_alter_subtitle_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/', validators=[core.vidapp.models.validate_video_extension]),
        ),
    ]
