# Generated by Django 5.1.1 on 2024-09-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidapp', '0005_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
